import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'models.dart';
import 'repository.dart';

class AuthGate extends StatefulWidget { final AppRepository repo; final AppThemeConfig theme; final ValueChanged<AppThemeConfig> onTheme; const AuthGate({super.key, required this.repo, required this.theme, required this.onTheme}); @override State<AuthGate> createState() => _AuthGateState(); }
class _AuthGateState extends State<AuthGate> { @override Widget build(BuildContext context) { if (widget.repo.user == null) return AuthPage(repo: widget.repo); if (widget.repo.loading || widget.repo.current == null) return const Center(child: CircularProgressIndicator()); return HomeShell(repo: widget.repo, theme: widget.theme, onTheme: widget.onTheme); } }

class AuthPage extends StatefulWidget { final AppRepository repo; const AuthPage({super.key, required this.repo}); @override State<AuthPage> createState() => _AuthPageState(); }
class _AuthPageState extends State<AuthPage> { final email = TextEditingController(), password = TextEditingController(), name = TextEditingController(); bool register = false, busy = false; String? error; Future<void> submit() async { setState(() { busy = true; error = null; }); try { if (register) { await widget.repo.db.auth.signUp(email: email.text.trim(), password: password.text, data: {'name': name.text.trim()}); } else { await widget.repo.db.auth.signInWithPassword(email: email.text.trim(), password: password.text); } } on AuthException catch (e) { setState(() => error = e.message); } finally { if (mounted) setState(() => busy = false); } } @override Widget build(BuildContext context) => Scaffold(body: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 440), child: Card(margin: const EdgeInsets.all(24), child: Padding(padding: const EdgeInsets.all(24), child: Column(mainAxisSize: MainAxisSize.min, children: [Text('Lingayat Matrimony', style: Theme.of(context).textTheme.headlineSmall), const SizedBox(height: 8), Text(register ? 'Create your account' : 'Welcome back'), if (register) ...[const SizedBox(height: 18), TextField(controller: name, decoration: const InputDecoration(labelText: 'Name'))], const SizedBox(height: 12), TextField(controller: email, keyboardType: TextInputType.emailAddress, decoration: const InputDecoration(labelText: 'Email')), const SizedBox(height: 12), TextField(controller: password, obscureText: true, decoration: const InputDecoration(labelText: 'Password')), if (error != null) Padding(padding: const EdgeInsets.only(top: 12), child: Text(error!, style: TextStyle(color: Theme.of(context).colorScheme.error))), const SizedBox(height: 20), SizedBox(width: double.infinity, child: FilledButton(onPressed: busy ? null : submit, child: Text(busy ? 'Please wait…' : register ? 'Create account' : 'Sign in'))), TextButton(onPressed: () => setState(() => register = !register), child: Text(register ? 'Already have an account? Sign in' : 'Create an account'))]))))); }
}

class HomeShell extends StatefulWidget { final AppRepository repo; final AppThemeConfig theme; final ValueChanged<AppThemeConfig> onTheme; const HomeShell({super.key, required this.repo, required this.theme, required this.onTheme}); @override State<HomeShell> createState() => _HomeShellState(); }
class _HomeShellState extends State<HomeShell> { int tab = 0; @override Widget build(BuildContext context) { final pages = [DiscoverPage(repo: widget.repo), MatchesPage(repo: widget.repo), ProfilePage(repo: widget.repo), if (widget.repo.isAdmin) AdminPage(repo: widget.repo)]; return Scaffold(appBar: AppBar(title: const Text('Lingayat Matrimony', style: TextStyle(fontWeight: FontWeight.bold)), actions: [IconButton(icon: const Icon(Icons.dark_mode_outlined), onPressed: () => widget.onTheme(AppThemeConfig(seed: widget.theme.seed, dark: !widget.theme.dark))), IconButton(icon: const Icon(Icons.logout), onPressed: () => widget.repo.db.auth.signOut())]), body: pages[tab], bottomNavigationBar: NavigationBar(selectedIndex: tab, onDestinationSelected: (i) => setState(() => tab = i), destinations: [const NavigationDestination(icon: Icon(Icons.search), label: 'Discover'), const NavigationDestination(icon: Icon(Icons.favorite_outline), label: 'Matches'), const NavigationDestination(icon: Icon(Icons.person_outline), label: 'Profile'), if (widget.repo.isAdmin) const NavigationDestination(icon: Icon(Icons.admin_panel_settings_outlined), label: 'Admin')])); } }

class DiscoverPage extends StatefulWidget { final AppRepository repo; const DiscoverPage({super.key, required this.repo}); @override State<DiscoverPage> createState() => _DiscoverPageState(); }
class _DiscoverPageState extends State<DiscoverPage> { String q = ''; @override Widget build(BuildContext context) { final list = widget.repo.profiles.where((p) => '${p.name} ${p.city} ${p.education} ${p.occupation}'.toLowerCase().contains(q.toLowerCase())).toList(); return Column(children: [Padding(padding: const EdgeInsets.all(16), child: TextField(onChanged: (v) => setState(() => q = v), decoration: const InputDecoration(prefixIcon: Icon(Icons.search), hintText: 'Search by name, city, education…'))), Expanded(child: ListView.builder(padding: const EdgeInsets.symmetric(horizontal: 16), itemCount: list.length, itemBuilder: (_, i) => ProfileCard(profile: list[i], repo: widget.repo))]); } }

class ProfileCard extends StatelessWidget { final Profile profile; final AppRepository repo; const ProfileCard({super.key, required this.profile, required this.repo}); @override Widget build(BuildContext context) => Card(child: ListTile(contentPadding: const EdgeInsets.all(10), leading: Avatar(profile: profile, size: 64), title: Text('${profile.name}, ${profile.age}', style: const TextStyle(fontWeight: FontWeight.bold)), subtitle: Text('${profile.city} • ${profile.education}\n${profile.occupation}'), isThreeLine: true, trailing: IconButton(onPressed: () => repo.toggleShortlist(profile), icon: Icon(repo.shortlisted.contains(profile.id) ? Icons.favorite : Icons.favorite_border)), onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => DetailPage(profile: profile, repo: repo)))); }
class Avatar extends StatelessWidget { final Profile profile; final double size; const Avatar({super.key, required this.profile, required this.size}); @override Widget build(BuildContext context) { final url = profile.photos.isEmpty ? null : profile.photos.first; return CircleAvatar(radius: size / 2, backgroundImage: url == null ? null : NetworkImage(url), child: url == null ? const Icon(Icons.person) : null); } }

class DetailPage extends StatelessWidget { final Profile profile; final AppRepository repo; const DetailPage({super.key, required this.profile, required this.repo}); @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Profile')), body: ListView(padding: const EdgeInsets.all(20), children: [Avatar(profile: profile, size: 150), const SizedBox(height: 16), Text('${profile.name}, ${profile.age}', style: Theme.of(context).textTheme.headlineSmall), Text('${profile.city} • ${profile.education} • ${profile.occupation}'), const SizedBox(height: 16), Wrap(spacing: 8, children: [Chip(label: Text(profile.subCommunity)), Chip(label: Text(profile.maritalStatus)), if (profile.verified) const Chip(label: Text('Verified'))]), const SizedBox(height: 16), Text(profile.about), const SizedBox(height: 24), FilledButton.icon(onPressed: () async { await repo.interest(profile); if (context.mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Interest sent.'))); }, icon: const Icon(Icons.favorite), label: const Text('Express interest')), OutlinedButton.icon(onPressed: () async { final reason = await showDialog<String>(context: context, builder: (_) => const _ReportDialog()); if (reason != null) { await repo.report(profile, reason); if (context.mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Report submitted.'))); } }, icon: const Icon(Icons.flag_outlined), label: const Text('Report profile'))])); }
class _ReportDialog extends StatefulWidget { const _ReportDialog(); @override State<_ReportDialog> createState() => _ReportDialogState(); }
class _ReportDialogState extends State<_ReportDialog> { final c = TextEditingController(); @override Widget build(BuildContext context) => AlertDialog(title: const Text('Report profile'), content: TextField(controller: c, maxLines: 3, decoration: const InputDecoration(hintText: 'Tell moderators what happened')), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')), FilledButton(onPressed: () => c.text.trim().length < 5 ? null : Navigator.pop(context, c.text.trim()), child: const Text('Submit'))]); }

class MatchesPage extends StatefulWidget { final AppRepository repo; const MatchesPage({super.key, required this.repo}); @override State<MatchesPage> createState() => _MatchesPageState(); }
class _MatchesPageState extends State<MatchesPage> { String city = ''; @override Widget build(BuildContext context) => Column(children: [Padding(padding: const EdgeInsets.all(16), child: TextField(onChanged: (v) => setState(() => city = v), decoration: const InputDecoration(labelText: 'Filter by preferred city', prefixIcon: Icon(Icons.location_city)))), Expanded(child: ListView(padding: const EdgeInsets.symmetric(horizontal: 16), children: [const Text('Automatic matches', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)), for (final m in widget.repo.matches(city: city)) Card(child: ListTile(leading: Avatar(profile: m.profile, size: 48), title: Text('${m.profile.name}, ${m.profile.age}'), subtitle: Text('${m.score}% match • ${m.reasons.join(' • ')}'), trailing: IconButton(onPressed: () => widget.repo.toggleShortlist(m.profile), icon: Icon(widget.repo.shortlisted.contains(m.profile.id) ? Icons.favorite : Icons.favorite_border)))]))]); }

class ProfilePage extends StatelessWidget { final AppRepository repo; const ProfilePage({super.key, required this.repo}); @override Widget build(BuildContext context) { final p = repo.current!; return ListView(padding: const EdgeInsets.all(20), children: [Text('My profile', style: Theme.of(context).textTheme.headlineSmall), ProfileCard(profile: p, repo: repo), FilledButton.icon(onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => EditProfilePage(repo: repo, profile: p))), icon: const Icon(Icons.edit), label: const Text('Edit profile')), const SizedBox(height: 8), Text(p.status == 'approved' ? 'Your profile is published.' : 'Your profile is awaiting moderator approval.')]; } }

class EditProfilePage extends StatefulWidget { final AppRepository repo; final Profile profile; const EditProfilePage({super.key, required this.repo, required this.profile}); @override State<EditProfilePage> createState() => _EditProfilePageState(); }
class _EditProfilePageState extends State<EditProfilePage> { final form = GlobalKey<FormState>(); late final Map<String, TextEditingController> c; @override void initState() { super.initState(); final p = widget.profile; c = {for (final x in ['name','city','education','occupation','about','minAge','maxAge']) x: TextEditingController(text: {'name':p.name,'city':p.city,'education':p.education,'occupation':p.occupation,'about':p.about,'minAge':'${p.minAge}','maxAge':'${p.maxAge}'}[x])}; } @override void dispose() { for (final x in c.values) x.dispose(); super.dispose(); } Future<void> save() async { if (!form.currentState!.validate()) return; final p = widget.profile; p.name=c['name']!.text.trim(); p.city=c['city']!.text.trim(); p.education=c['education']!.text.trim(); p.occupation=c['occupation']!.text.trim(); p.about=c['about']!.text.trim(); p.minAge=int.parse(c['minAge']!.text); p.maxAge=int.parse(c['maxAge']!.text); await widget.repo.saveProfile(p); if (mounted) Navigator.pop(context); } @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Edit profile')), body: Form(key: form, child: ListView(padding: const EdgeInsets.all(20), children: [for (final item in c.entries) Padding(padding: const EdgeInsets.only(bottom: 12), child: TextFormField(controller: item.value, maxLines: item.key == 'about' ? 4 : 1, keyboardType: item.key.contains('Age') ? TextInputType.number : TextInputType.text, decoration: InputDecoration(labelText: item.key == 'minAge' ? 'Minimum preferred age' : item.key == 'maxAge' ? 'Maximum preferred age' : item.key[0].toUpperCase() + item.key.substring(1)), validator: (v) { if (v == null || v.trim().isEmpty) return 'Required'; if (item.key.contains('Age') && (int.tryParse(v) == null || int.parse(v) < 18 || int.parse(v) > 80)) return 'Enter an age from 18 to 80'; return null; })), FilledButton(onPressed: save, child: const Text('Save profile'))])); } }

class AdminPage extends StatelessWidget { final AppRepository repo; const AdminPage({super.key, required this.repo}); @override Widget build(BuildContext context) => ListView(padding: const EdgeInsets.all(20), children: [Text('Moderation queue', style: Theme.of(context).textTheme.headlineSmall), for (final p in repo.profiles) Card(child: ListTile(title: Text('${p.name}, ${p.age}'), subtitle: Text('${p.city} • ${p.status}'), trailing: Row(mainAxisSize: MainAxisSize.min, children: [IconButton(onPressed: () => repo.moderate(p, 'rejected'), icon: const Icon(Icons.close)), IconButton(onPressed: () => repo.moderate(p, 'approved'), icon: const Icon(Icons.check))]))) ]); }
